# balbino

name: flask ci cd example alpha - dev workflow

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    step:
    - uses: actions/checkout@v2
    - name: setup python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9